# Model
model_name_or_path: swiss-ai/Apertus-8B-Instruct-2509
attn_implementation:  flash_attention_2
torch_dtype: bfloat16
use_peft: false

# Dataset
dataset_name: openlifescienceai/MedQA-USMLE-4-options-hf
dataset_config: null 
dataset_num_proc: 12
dataset_train_split: train    
dataset_test_split: validation

# Hyperparameters
learning_rate: 2.0e-5
gradient_checkpointing: false
num_train_epochs: 3.0
max_steps: 500
logging_steps: 1
per_device_train_batch_size: 1
gradient_accumulation_steps: 16

# FSDP
fsdp: "full_shard auto_wrap"
fsdp_config:
  activation_checkpointing: true
  backward_prefetch: "backward_pre"
  transformer_layer_cls_to_wrap: "ApertusDecoderLayer"

# Seq length & scheduler
max_length: 4096
warmup_ratio: 0.1
lr_scheduler_type: cosine_with_min_lr
lr_scheduler_kwargs:
  min_lr_rate: 0.1

# Output & logging
output_dir: output/apertus_full_8B
seed: 42
report_to: # add wandb to log run on Weigths and Biases
  - wandb
run_name: "ap-medqa-full_8B"  
logging_steps: 5                # how often to log train loss
eval_strategy: "steps"          # or "epoch"
eval_steps: 25                  # how often to log eval metrics
save_strategy: "steps"
save_steps: 25
load_best_model_at_end: true
metric_for_best_model: "eval_medqa_mcq_accuracy"
greater_is_better: true   
save_total_limit: 2
do_eval: true
log_on_each_node: false
logging_strategy: "steps"